### ISSUE TITLE
Fix strictMultiaddr

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-websocket-star#15]

**Comment by diasdavid** [comment]
@mkg20001 what's this feature exactly?

**Comment by mkg20001** [comment]
It verifies the multiaddr using `mafmt.WebSocketStar.matches(ma)` but that seems broken for some reason.

**Comment by diasdavid** [comment]
Opened https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/issues/4
