### ISSUE TITLE
Discovery is not working as expected

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websocket-star#18]
Enabling this test will make the suite fail with timeout
https://github.com/libp2p/js-libp2p-websocket-star/blob/master/test/discovery.spec.js

**Comment by mkg20001** [comment]
After doing some debugging I found out that for some reason the `peers` object has two different values for every peer (`log('send', multiaddr, Object.keys(peers).length, 'peer(s)'); log(Object.keys(peers))`)
![wtf](https://user-images.githubusercontent.com/7735145/30749092-9a1556b4-9fb2-11e7-8345-77382c7005a4.png)
