### ISSUE TITLE
Needs rendezvous point hosted just like webrtc-star

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websocket-star#2]

**Comment by mkg20001** [comment]
I'm already hosting one at `/libp2p-webrtc-star/ip4/148.251.206.162/tcp/9090/ws/`. Isn't that enough?

**Comment by diasdavid** [comment]
Ideally we should host one that uses a domain (so that it can be used in the browser) and that is instrumented so that we can monitor it.

Also, it should use /libp2p-websockets-star/ and not webrtc-star

**Comment by mkg20001** [comment]
> Also, it should use /libp2p-websockets-star/ and not webrtc-star

Yes but that's an issue that needs to be solved in multiaddr
```js
> require("multiaddr")("/libp2p-websocket-star/ip4/148.251.206.162/tcp/9090/ws/")
Error: no protocol with name: libp2p-websocket-star
```

**Comment by diasdavid** [comment]
@mkg20001 you are welcome to submit a PR :) Make sure to submit a PR for the main table as well https://github.com/multiformats/multicodec

**Comment by mkg20001** [comment]
@diasdavid But webrtc-star is nowhere to be seen in the table/readme

**Comment by mkg20001** [comment]
I've switched the signaling server to https (ws-star-signal-1.servep2p.com and ws-star-signal-2.servep2p.com)

**Comment by diasdavid** [comment]
Let's continue tracking this in https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/pull/1
