### ISSUE TITLE
Replace isIP by mafmt match call

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websocket-star#20]
This func -- https://github.com/libp2p/js-libp2p-websocket-star/blob/master/src/utils.js#L8 -- is duplicating what mafmt does.

**Comment by mkg20001** [comment]
Actually the reason the code is in there is because I have just copied https://github.com/multiformats/js-multiaddr/blob/master/src/index.js#L355-L369 and removed the `if (protos.length != 2)`

**Comment by diasdavid** [comment]
It's fine to get inspiration from other modules. You can save lines of code by using mafmt which was designed to check that :)

**Comment by mkg20001** [comment]
Done that
