### ISSUE TITLE
Need perms to publish to npm

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websocket-star#21]
@mkg20001 can you share publish perms with me? https://www.npmjs.com/package/libp2p-websocket-star

My npm username is [`daviddias`](https://www.npmjs.com/~daviddias)

**Comment by mkg20001** [comment]
Done. Could you add me to libp2p-websocket-star-rendezvous? My username is `mkg20001` on npm

**Comment by diasdavid** [comment]
Done! 

```sh
> npm owner add mkg20001
+ mkg20001 (libp2p-websocket-star-rendezvous)
```

Thank you!
