### ISSUE TITLE
Listening in two different multiaddrs that point to two different rendezvous points breaks

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websocket-star#25]
Due to this assumption -- https://github.com/libp2p/js-libp2p-websocket-star/blob/master/src/index.js#L146 -- that this transport will only use one multiaddr, if a user decides to use two rendezvous points, it will break the connections from the first.

**Comment by mkg20001** [comment]
I'm unsure if it breaks. Is one **listener** (not transport) supposed to listen on multiple multiaddrs at the same time?

**Comment by diasdavid** [comment]
You are right, I misread this part, now it is more clear with one class per file :)
