### ISSUE TITLE
If there are Crypto Puzzles for Auth, these need to be documented

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websocket-star#26]
It is unclear right now without having clear docs from the dev what is intended here: https://github.com/libp2p/js-libp2p-websocket-star/blob/master/src/index.js#L68-L118 and so it is hard to add more tests and/or refactor without knowing if we are breaking your original expectations.

**Comment by mkg20001** [comment]
Is [this](https://github.com/libp2p/js-libp2p-websocket-star/blob/master/docs/CRYPTO.md) sufficient?

**Comment by mkg20001** [comment]
@diasdavid ?
