### ISSUE TITLE
empty Object returns as an error when integrating with js-ipfs

### ISSUE THREAD

**Issue by ya7ya** [libp2p/js-libp2p-websocket-star#31]
Hey @mkg20001 , Thanks for the cool module, I noticed the following when trying to use this with `js-ipfs`,

it returns an err when triggering [`listen`](https://github.com/libp2p/js-libp2p-websocket-star/blob/master/src/listener.js#L194) , the err is just an empty object `{}` and I traced it back to the callback function on [`this.io.emit('ss-join', maStr, pubKeyStr, (err, sig) => {`](https://github.com/libp2p/js-libp2p-websocket-star/blob/master/src/listener.js#L93) 

if you simply ignore that empty object error `if (err && Object.keys(err).length !== 0)` , it works but i'm not sure thats a proper fix , and also `sig` returned `undefined` .

Thanks for your help, I appreciate the hard work 👍

**Comment by mkg20001** [comment]
This empty object might be the result of the server returning an error object and JSON.stringify turning it into an empty object.
I will look into the error later.
Btw are you running the latest version on master or npm?

**Comment by ya7ya** [comment]
In running the npm version, but I can try the latest one.

**Comment by mkg20001** [comment]
I think the error could be caused by using `ws-star-signal-1.servep2p.com` as it's running an older version of ws-star and using `ws-star-signal-3.servep2p.com` instead should fix that.
Also are you creating the websocket-star transport with the id as argument (`new WStar{ id: peerId })`)?

**Comment by mkg20001** [comment]
@ya7ya I've solved the empty object bug. Now it should return a string or an error (in the latest git version)

**Comment by ya7ya** [comment]
@mkg20001 Thanks dude, I'll check it out. and yes I was using the peerId in the constructor as instructed 👍

**Comment by mkg20001** [comment]
Should have been fixed. Reopen if it regresses.
