### ISSUE TITLE
peer not leaving

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p-websocket-star#34]
I've been doing some disconnect / reconnect tests to try and migrate Peerpad to this transport.
The initial discovery seams to work ok.
But once I close a peer, that peer does not leave from the peer list of other peers, which makes it impossible for the peer to be reported as (re-)discovered once it reconnects.

**Comment by diasdavid** [comment]
Thanks for catching this @pgte! @mkg20001 seems that Connections are never shutdown and that peers returning do not fire the discovery event.

**Comment by mkg20001** [comment]
@pgte I have fixed the error in my lib `socket.io-pull-stream` and upgraded deps here. The lib already has a test for disconnect. Do we need a test here too?

**Comment by pgte** [comment]
@mkg20001 Awesome!
It would be super nice to have a test here, so that we don't get a regression some time in the future.. :)

**Comment by mkg20001** [comment]
@pgte Tests added
@diasdavid Can you deploy the current version of libp2p-websocket-star-rendezvous to the ipfs cloud? This would fix the bug without upgrading the clients.

**Comment by diasdavid** [comment]
Awesome news @pgte @mkg20001 \o/

Tagging myself here. Will do ASAP.

**Comment by pgte** [comment]
@mkg20001 @diasdavid I'm observing some random message loss inside one message that doesn't happen when I'm using a self-hosted rendez-vous server.
I cannot reproduce this loss locally.
Since I suspect this may be related to the latest fix in the rendez-vous server, I'm going to wait until the infrastructure is updated to test this one again..

**Comment by mkg20001** [comment]
@pgte There was a race condition in the data-queue module. I have fixed that in socket.io-pull-stream

**Comment by pgte** [comment]
@mkg20001 tested with newly-deployed rendezvous server and reconnecting is looking good.
Thank you for the fix! 🌟🌟🌟🌟🌟

**Comment by diasdavid** [comment]
sweeet! :D
