### ISSUE TITLE
Tests are failing and Code Coverage is kind of low

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websocket-star#44]
@mkg20001 wanna take a look into that?

**Comment by mkg20001** [comment]
Does https://github.com/libp2p/js-libp2p-websocket-star/pull/43 improve it?

**Comment by mkg20001** [comment]
Note that the tests are in libp2p-websocket-star (rewrite-v2 branch) and not here in the server otherwise they would be duplicated. Got any ideas of how to resolve that?

**Comment by diasdavid** [comment]
We strive to have Master always green on CI. #43 might improve it but the reality is that it is blocked until https://github.com/libp2p/js-libp2p/issues/159.

Can you improve the master branch as is to make sure the tests there are 100% passing?

**Comment by mkg20001** [comment]
Actually #43 isn't blocked so much by that because the `.__setSwarm` hack works pretty well and considering this module is actually a giant hack (because p2p-circuit is already a thing, maybe we should remove relay here and rename this to webMDNS? https://github.com/libp2p/js-libp2p-webrtc-star/issues/128#issuecomment-363779712) so I don't know why we shouldn't use that hack to fix the hack...

**Comment by mkg20001** [comment]
Btw, to fix this module I need https://github.com/whyrusleeping/js-mafmt/pull/21 merged and released first

**Comment by diasdavid** [comment]
mafmt v4.0.0 published.

**Comment by mkg20001** [comment]
Tests should be now (_that really depends whether or not travis is in good mood_) fixed

**Comment by diasdavid** [comment]
Thank you :) 

For the future, please avoid pushing directly into master.

**Comment by diasdavid** [comment]
Coverage is still kind of low (69%)

**Comment by mkg20001** [comment]
Didn't we want to get rid of ws-star anyway? Does this even matter then?

**Comment by jacobheun** [comment]
Tests in master are stable, https://ci.ipfs.team/blue/organizations/jenkins/libp2p%2Fjs-libp2p-websocket-star/activity?branch=master, and coverage is >80%.

Closing this.
