### ISSUE TITLE
closing the listener drops underlying connections

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p-websocket-star#49]
When closing a listener, all the underlying connections are dropped.

Instead, this should behave like webrtc-star, where the peer connections are maintained. (in Webrtc-star, the severed connection is to the discovery service, effectively preventing from knowing new peers.)

**Comment by mkg20001** [comment]
The connections are going through the server, to which the connection gets closed. If the intent is to not discover any more peers then the user should just call `ws-star.discovery.stop(cb)` instead.

**Comment by pgte** [comment]
I think that the purpose of stopping a listener is to say "don't accept any more connections", and not "do that AND close all the existing connections".

More context: [this discussion](https://github.com/libp2p/interface-transport/issues/34#issuecomment-383511510).

**Comment by mkg20001** [comment]
But if the listener doesn't disconnect on close, when should it do it then?

**Comment by pgte** [comment]
Well, libp2p-switch keeps track of all the connections, so what's stopping the user or a connection-manager to kill any (or all) connections?

For instance, this is the current behaviour of the websocket-star transport, where `listener.close()` does not kill connections to other peers.

The behaviour would be analogous of this in the node.js world would be the [`server.close()`](https://nodejs.org/api/net.html#net_server_close_callback) (without needing to pass a callback).

**Comment by mkg20001** [comment]
> The behaviour would be analogous of this in the node.js world would be the server.close() (without needing to pass a callback).

So the connection to the relay should be closed only if 1. all connections are disconnected and 2. the listener is closed?

**Comment by pgte** [comment]
Yes, I suppose that's how it should be implemented... Thoughts?

**Comment by mkg20001** [comment]
@pgte Implemented in #53

**Comment by jacobheun** [comment]
This is available via #53 in 0.9.0.
