### ISSUE TITLE
Using libp2p-websocket-star with Discovery-Channel

### ISSUE THREAD

**Issue by solydtech** [libp2p/js-libp2p-websocket-star#67]
Hi,

I am looking to use this mdns with Discovery Channel [link](https://github.com/maxogden/discovery-channel).

Is there any starting reference?

**Comment by jacobheun** [comment]
libp2p has an [mdns module](https://github.com/libp2p/js-libp2p-mdns). You can see it's configuration and usage in the [mdns discovery example](https://github.com/libp2p/js-libp2p/blob/v0.24.3/examples/discovery-mechanisms/2.js#L24) in the js-libp2p repo.

**Comment by mkg20001** [comment]
Closing this, since old and unreleated
