### ISSUE TITLE
Add query option for socket.io client library

### ISSUE THREAD

**Issue by pashoo2** [libp2p/js-libp2p-websocket-star#78]
It's necessary to add a query option, to allow for a server side to define wich query has come - it it from the 'js-libp2p-websocket-star' and 'js-libp2p-webrtc-star'.
For example, i wrote the proxy server and it's necessary to decide which server must handle the query received - 'libp2p-websocket-star-rendezvous' or 'star-signal' instance.
At now i've added this configuration to the library:
const sioOptions = {
  transports: ['websocket'],
  'force new connection': true,
  query: {
    ws: true,
  },
};
and use the 'patch-package' to resolve the issue

**Comment by pashoo2** [comment]
Query parameter will be added to the js-libp2p-webrtc-star according to the issue https://github.com/libp2p/js-libp2p-webrtc-star/issues/186

**Comment by jacobheun** [comment]
Closing this. The repo is currently deprecated with only bug fix support.
